### ISSUE TITLE
haddock fails to build with ghc-8.0

### ISSUE THREAD

**Issue by juhp** [haskell/zlib#72]
This is low priority but I still build some of my projects with ghc-8.0 in github for example: [pagure-hs](https://github.com/juhp/pagure-hs/actions/runs/8957670650/job/24601008852): I still need to find out why it failed.

`Error: cabal: Failed to build documentation for zlib-0.7.1.0 (which is required by pagure-0.1.2).`

Also this is certainly not a request to stop supporting 8.0: building the docs still for 8.0 is very much a corner case by now i would say, still if this is easily fixable it might be nice to address in a future release.

**Comment by Bodigrim** [comment]
IIRC it has something to do with Haddock from GHC 8.0 unable to support `@since` in `deriving` clause like this:

https://github.com/haskell/zlib/blob/f38bd203950c30d3b2b2c54f94783d0f142ce400/zlib/Codec/Compression/Zlib/Internal.hs#L117-L123

This could in principle be fixed with CPP, but I don't believe it's a good idea, so most likely won't do.
